/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuildMap.java
 *
 * Created on May 8, 2010, 7:24:43 AM
 */

package View.BuildMode;

import Model.Map.Map;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicBorders.FieldBorder;
import Support.*;
import View.MainMenu;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author user
 */
public class BuildMap extends javax.swing.JFrame implements MouseListener, MouseMotionListener, ActionListener{

    /** Creates new form BuildMap */
    public BuildMap(MainMenu parent) {
        this.parent = parent; /* Pointed parent Window */
        initComponents();

        /* Initial Map */
        mapLogic = new Map(); /* Create map by default */
        paintMap(); /* Paint Map */

        /* Add Mouse Listener */
        contentPanel.addMouseListener(this);
        contentPanel.addMouseMotionListener(this);

        /* Add Action Listener */
        rumputButton.addActionListener(this);
        airButton.addActionListener(this);
        lumpurButton.addActionListener(this);
        pohonButton.addActionListener(this);
        castle1Button.addActionListener(this);
        castle2Button.addActionListener(this);
        castle3Button.addActionListener(this);
        castle4Button.addActionListener(this);

        /* Set Action Command Name */
        rumputButton.setActionCommand(Map.GetString(Map.RUMPUT));
        airButton.setActionCommand(Map.GetString(Map.AIR));
        lumpurButton.setActionCommand(Map.GetString(Map.LUMPUR));
        pohonButton.setActionCommand(Map.GetString(Map.POHON));
        castle1Button.setActionCommand(Map.GetString(Map.CASTLE1));
        castle2Button.setActionCommand(Map.GetString(Map.CASTLE2));
        castle3Button.setActionCommand(Map.GetString(Map.CASTLE3));
        castle4Button.setActionCommand(Map.GetString(Map.CASTLE4));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        Load = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        changeterrainPanel = new javax.swing.JPanel();
        airButton = new javax.swing.JButton();
        pohonButton = new javax.swing.JButton();
        lumpurButton = new javax.swing.JButton();
        rumputButton = new javax.swing.JButton();
        castle1Button = new javax.swing.JButton();
        castle3Button = new javax.swing.JButton();
        castle2Button = new javax.swing.JButton();
        castle4Button = new javax.swing.JButton();
        selectAllButton = new javax.swing.JButton();
        deselectButton = new javax.swing.JButton();
        randomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(Load, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Load)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scroll.setAutoscrolls(true);

        contentPanel.setBackground(new java.awt.Color(0, 0, 0));
        contentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        scroll.setViewportView(contentPanel);

        airButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/air.png"))); // NOI18N
        airButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        airButton.setMaximumSize(new java.awt.Dimension(30, 30));
        airButton.setMinimumSize(new java.awt.Dimension(30, 30));
        airButton.setPreferredSize(new java.awt.Dimension(30, 30));

        pohonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pohon.png"))); // NOI18N
        pohonButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pohonButton.setMaximumSize(new java.awt.Dimension(30, 30));
        pohonButton.setMinimumSize(new java.awt.Dimension(30, 30));
        pohonButton.setPreferredSize(new java.awt.Dimension(30, 30));

        lumpurButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lumpur.png"))); // NOI18N
        lumpurButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lumpurButton.setMaximumSize(new java.awt.Dimension(30, 30));
        lumpurButton.setMinimumSize(new java.awt.Dimension(30, 30));
        lumpurButton.setPreferredSize(new java.awt.Dimension(30, 30));

        rumputButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rumput.png"))); // NOI18N
        rumputButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rumputButton.setMaximumSize(new java.awt.Dimension(30, 30));
        rumputButton.setMinimumSize(new java.awt.Dimension(30, 30));
        rumputButton.setPreferredSize(new java.awt.Dimension(30, 30));

        castle1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/castle1.png"))); // NOI18N
        castle1Button.setMaximumSize(new java.awt.Dimension(30, 30));
        castle1Button.setMinimumSize(new java.awt.Dimension(30, 30));
        castle1Button.setPreferredSize(new java.awt.Dimension(30, 30));

        castle3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/castle3.png"))); // NOI18N
        castle3Button.setMaximumSize(new java.awt.Dimension(30, 30));
        castle3Button.setMinimumSize(new java.awt.Dimension(30, 30));
        castle3Button.setPreferredSize(new java.awt.Dimension(30, 30));

        castle2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/castle2.png"))); // NOI18N

        castle4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/castle4.png"))); // NOI18N
        castle4Button.setMaximumSize(new java.awt.Dimension(30, 30));
        castle4Button.setMinimumSize(new java.awt.Dimension(30, 30));
        castle4Button.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout changeterrainPanelLayout = new javax.swing.GroupLayout(changeterrainPanel);
        changeterrainPanel.setLayout(changeterrainPanelLayout);
        changeterrainPanelLayout.setHorizontalGroup(
            changeterrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeterrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeterrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeterrainPanelLayout.createSequentialGroup()
                        .addComponent(pohonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rumputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(castle3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(castle4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changeterrainPanelLayout.createSequentialGroup()
                        .addComponent(airButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lumpurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(castle1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(castle2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeterrainPanelLayout.setVerticalGroup(
            changeterrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeterrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeterrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(castle1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lumpurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(castle2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changeterrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pohonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rumputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(castle3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(castle4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        selectAllButton.setText("Select All");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        deselectButton.setText("Deselect");
        deselectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectButtonActionPerformed(evt);
            }
        });

        randomButton.setText("Random");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeterrainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectAllButton)
                    .addComponent(deselectButton)
                    .addComponent(randomButton))
                .addGap(614, 614, 614))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeterrainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(selectAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deselectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomButton)
                        .addGap(65, 65, 65))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        this.dispose(); /* Close this window */
        parent.setVisible(true) /* Show parent Window */;
    }//GEN-LAST:event_backButtonMouseClicked

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        /* Call OpenSize Window */
        InputSize input = new InputSize(this);
        input.setVisible(true);

        /* Set This Window Disable */
        setEnabled(false);
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        /* Save Map */
        IOObject.Save(mapLogic, "tes.map");
        this.setEnabled(true);
        SaveMap save = new SaveMap(this);
        save.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        /* Create & Show LoadMap Window */
        LoadMap load = new LoadMap(this);
        load.setVisible(true);

        /* Disabled this Window */
        this.setEnabled(false);
    }//GEN-LAST:event_LoadActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        /* Get All Component in contentPanel */
        Component[] list = contentPanel.getComponents();

        JLabel l;

        /* Clear All selected Label */
        selected.clear();

        /* Select All Map components */
        for (int i=0;i<list.length;++i) {
            l = (JLabel)list[i];
            l.setBorder(new FieldBorder(Color.BLACK, Color.BLACK, Color.BLACK, Color.BLACK)); /* Set border for Label l */

            /* Add l to selected List */
            selected.add(l);
        }
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void deselectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectButtonActionPerformed
        JLabel l;

        for (int i=0;i<selected.size();++i) {
            l = selected.get(i);
            l.setBorder(null); /* Erase Border */
        }

        /* Clear selected */
        selected.clear();
    }//GEN-LAST:event_deselectButtonActionPerformed

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        /* Random */
        mapLogic.SetMapRandom();

        /* Repaint */
        paintMap();
    }//GEN-LAST:event_randomButtonActionPerformed

    public void mouseClicked(MouseEvent e) {}

    public void mouseEntered(MouseEvent e) {}

    public void mouseExited(MouseEvent e) {}

    public void mousePressed(MouseEvent e) {
        /* Get Component at mouse click's position */
        Component c = contentPanel.getComponentAt(e.getX(), e.getY());

        /* Create temporary label*/
        JLabel l;

        
        if (c instanceof JLabel) { /* Cek c is a Label */
             l = (JLabel)c; /* l point to c */

             /* Cek if l is selected */
            if (selected.contains(l)) { /* Cek is selected */
                l.setBorder(null); /* Erase border */
                selected.remove(l); /* Remove Label l from selected List */
            } else { /* Cek is not yet selected */
                l.setBorder(new FieldBorder(Color.BLACK, Color.BLACK, Color.BLACK, Color.BLACK)); /* Set border for Label l */
                selected.add(l); /* Add Label l to selected List */
            }
        } else { /* c isn't a Label */
            return;
        }
    }

    public void mouseReleased(MouseEvent e) {}

    public void mouseDragged(MouseEvent e) {
        /* Get Label at mouse dragged's point */
        Component c = contentPanel.getComponentAt(e.getX(), e.getY());
        JLabel l;

        if (c instanceof JLabel) {
            l = (JLabel)c;
            if (!selected.contains(l)) { /* l is not yet selected */
                l.setBorder(new FieldBorder(Color.BLACK, Color.BLACK, Color.BLACK, Color.BLACK)); /* Set border for Label l */
                selected.add(l);
            }
        }
    }

    public void mouseMoved(MouseEvent e) {}

    public void actionPerformed(ActionEvent e) {
        JLabel l;

        /* Change image selected terrain or building and its Value in mapLogic */
        for (int i=0;i<selected.size();++i) {
            l = selected.get(i);
            int n = Map.GetContentNumber(e.getActionCommand());

            if (!mapLogic.IsCastle(n) || !mapLogic.IsCastleIn(n)) {
                l.setIcon(ImageSupport.createImageIcon(e.getActionCommand()+".png", null));
                Point gridpoint = Converter.PointToGrid(l.getX(), l.getY());
                mapLogic.SetContent(gridpoint.x, gridpoint.y, Map.GetContentNumber(e.getActionCommand()));
            }

            /* Remove border selected Label */
            l.setBorder(null);
        }

        /* Remove All Label from selected List */
        selected.clear();
    }

    public void createContent(int x, int y, int width, int height, String iconName) {
        JLabel label = new JLabel(ImageSupport.createImageIcon(iconName+".png", null));
        label.setBounds(x, y, width, height);
        contentPanel.add(label);
    }

    public void paintMap() {
        /* Remove all component in content Panel */
        contentPanel.removeAll();
        contentPanel.repaint();

        /* Add new component(terrain & building ) in content Panel */
        for (int i=0;i<mapLogic.GetWidth();++i) {
            for (int j=0;j<mapLogic.GetHeight();++j) {
                createContent(i*ImageSupport.IMAGE_WIDTH, j*ImageSupport.IMAGE_HEIGHT, ImageSupport.IMAGE_WIDTH, ImageSupport.IMAGE_HEIGHT, Map.GetString(mapLogic.GetContent(i, j)));
            }
        }
        contentPanel.repaint();

        /* Set new Size for contentPanel */
        Dimension d = new Dimension(ImageSupport.IMAGE_WIDTH*mapLogic.GetWidth(), ImageSupport.IMAGE_HEIGHT*mapLogic.GetHeight());
        contentPanel.setPreferredSize(d);
        scroll.setViewportView(contentPanel);
    }

    public Map GetMap() {
        return mapLogic;
    }

    public void SetMap(Map map) {
        mapLogic = map;
    }

    public void SetMapName(String mapName) {
        this.mapName = mapName;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load;
    private javax.swing.JButton airButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton castle1Button;
    private javax.swing.JButton castle2Button;
    private javax.swing.JButton castle3Button;
    private javax.swing.JButton castle4Button;
    private javax.swing.JPanel changeterrainPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deselectButton;
    private javax.swing.JButton lumpurButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newButton;
    private javax.swing.JButton pohonButton;
    private javax.swing.JButton randomButton;
    private javax.swing.JButton rumputButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton selectAllButton;
    // End of variables declaration//GEN-END:variables

    private MainMenu parent;
    private ArrayList<JLabel> selected = new ArrayList<JLabel>();
    private Map mapLogic;
    private String mapName = null;
}
