/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Play.java
 *
 * Created on May 7, 2010, 7:50:57 PM
 */

package View.PlayMode;

import Model.Map.Map;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import Support.ImageSupport;
import View.MainMenu;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class Play extends javax.swing.JFrame implements ActionListener {

    /** Creates new form Play */
    public Play(MainMenu parent) {
        initComponents();
        this.parent = parent;
        InitinalTerrain();
        l = new JLabel(ImageSupport.createImageIcon("../Image/air.png", null));
        timer = new Timer(10, this);
        timer.setActionCommand("timer");
        timer.setInitialDelay(30 * 7);
        timer.setCoalesce(true);
        layerpane.add(l, JLayeredPane.DRAG_LAYER);
        l.setBounds(31, 31, 30, 30);
        terraincontainer.setPreferredSize(new Dimension(600, 600));
        terraincontainer.setBounds(0, 0, 600, 600);
        layerpane.setPreferredSize(new Dimension(600, 600));
        System.out.println(layerpane.getComponentsInLayer(JLayeredPane.DEFAULT_LAYER)[0].getComponentAt(0, 0));
        pack();
        //timer.start();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        goyang = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        layerpane = new javax.swing.JLayeredPane();
        terraincontainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dunno");
        setResizable(false);

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        goyang.setText("goyang");
        goyang.setToolTipText("Untuk goyang");
        goyang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goyangMousePressed(evt);
            }
        });

        layerpane.setToolTipText("Scroll");

        javax.swing.GroupLayout terraincontainerLayout = new javax.swing.GroupLayout(terraincontainer);
        terraincontainer.setLayout(terraincontainerLayout);
        terraincontainerLayout.setHorizontalGroup(
            terraincontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        terraincontainerLayout.setVerticalGroup(
            terraincontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        terraincontainer.setBounds(0, 0, -1, -1);
        layerpane.add(terraincontainer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        scroll.setViewportView(layerpane);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goyang)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(818, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(goyang)
                        .addGap(342, 342, 342)
                        .addComponent(backButton))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        timer.stop();
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void goyangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goyangMousePressed
        l.setLocation(l.getX()+1, l.getY()+1);
    }//GEN-LAST:event_goyangMousePressed

    private void InitinalTerrain() {
        //terraincontainer.setLayout(new GridBagLayout());
        for (int i=0;i<20;++i) {
            for (int j=0;j<20;++j) {
                JLabel label = new JLabel(ImageSupport.createImageIcon("../Image/rumput.png", "rumput segar"));
                label.setOpaque(true);
                label.setBounds(i*30, j*30, 30, 30);
                terraincontainer.add(label);
            }
        }
        //terraincontainer.setBounds(0, 0, 1000, 1000);
    }

    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("timer")) {
            l.setLocation(l.getX()+1, l.getY()+1);
            if (l.getX()>210) {
                timer.stop();
            }
        } else {
            System.out.println("tes");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton goyang;
    private javax.swing.JLayeredPane layerpane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel terraincontainer;
    // End of variables declaration//GEN-END:variables
    private MainMenu parent;
    private Map mapterrain = new Map(15, 15);
    private int pos = 0;
    private JLabel l;
    Timer timer;
}
